var Const_JSON = [
    {"Name":"No Remorse","Constant":"14.0","Difficulty":"LUNATIC","Hot":"0"},
    {"Name":"初音ミクの激唱","Constant":"14","Difficulty":"LUNATIC","Hot":"0"},
    {"Name":"ナイト・オブ・ナイツ","Constant":"13.9","Difficulty":"LUNATIC","Hot":"0"},
    {"Name":"ようこそジャパリパークへ","Constant":"13","Difficulty":"LUNATIC","Hot":"0"},
    {"Name":"Sakura Fubuki","Constant":"13.7","Difficulty":"LUNATIC","Hot":"0"},
    {"Name":"Calamity Fortune","Constant":"14","Difficulty":"LUNATIC","Hot":"0"},
    {"Name":"STARTLINER","Constant":"12.8","Difficulty":"LUNATIC","Hot":"0"},
    {"Name":"からくりピエロ","Constant":"12.9","Difficulty":"LUNATIC","Hot":"0"},
    {"Name":"緋蜂","Constant":"14.7","Difficulty":"LUNATIC","Hot":"0"},
    {"Name":"39","Constant":"12.2","Difficulty":"MASTER","Hot":"0"},
    {"Name":"＊ハロー、プラネット。","Constant":"12","Difficulty":"MASTER","Hot":"0"},
    {"Name":"7thSense","Constant":"14","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ADAMAS","Constant":"13.1","Difficulty":"MASTER","Hot":"1"},
    {"Name":"Aenbharr","Constant":"14.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Ai Nov","Constant":"13.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"AMAZING MIGHTYYYY!!!!","Constant":"13.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Äventyr","Constant":"12.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Bad Apple!! feat.nomico","Constant":"12.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Baqeela","Constant":"13.9","Difficulty":"MASTER","Hot":"1"},
    {"Name":"BLACK SHOUT","Constant":"11.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"BOUNCE & DANCE","Constant":"13.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Brain Power","Constant":"13.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Calamity Fortune","Constant":"13.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Chelly spLash♪♪","Constant":"13.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"CiRCLING","Constant":"12","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Colors","Constant":"12.1","Difficulty":"MASTER","Hot":"0"},
    {"Name":"conflict","Constant":"13.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Connecting Happy!!","Constant":"12.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Cream+Mint","Constant":"11.1","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Cyberozar","Constant":"13.1","Difficulty":"MASTER","Hot":"0"},
    {"Name":"DAYBREAK FRONTLINE","Constant":"13","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Dazzle hop","Constant":"14.2","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Death Doll","Constant":"13.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Desperado Waltz","Constant":"14.3","Difficulty":"MASTER","Hot":"1"},
    {"Name":"Destiny Runner","Constant":"13.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Doll's Destiny","Constant":"12.8","Difficulty":"MASTER","Hot":"1"},
    {"Name":"Dolphika","Constant":"13.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Dragoon","Constant":"12.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"DreamRiser","Constant":"11.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Energy Booster ～ 上海紅茶館","Constant":"12.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Everlasting Today","Constant":"14.1","Difficulty":"MASTER","Hot":"0"},
    {"Name":"fantastic dreamer","Constant":"12.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"First Twinkle","Constant":"11.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"FREEDOM DiVE (tpz Overcute Remix)","Constant":"14.2","Difficulty":"MASTER","Hot":"1"},
    {"Name":"fulgente","Constant":"12.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"GAME IS LIFE","Constant":"12.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Garakuta Doll Play","Constant":"14.1","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Gate of Doom","Constant":"13.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"GEOMETRIC DANCE","Constant":"14.5","Difficulty":"MASTER","Hot":"1"},
    {"Name":"GO! GO! MANIAC","Constant":"13.5","Difficulty":"MASTER","Hot":"1"},
    {"Name":"ＧＯ！ＧＯ！ラブリズム♥","Constant":"11.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"God knows...","Constant":"13","Difficulty":"MASTER","Hot":"0"},
    {"Name":"GOODRAGE","Constant":"14","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Grand symphony","Constant":"12.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"GranFatalité","Constant":"12.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Grip & Break down !!","Constant":"12","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Halcyon","Constant":"13.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Hand in Hand","Constant":"12.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"HARMONIZE","Constant":"12.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Hello, Morning","Constant":"12.7","Difficulty":"MASTER","Hot":"1"},
    {"Name":"Help me, ERINNNNNN!!","Constant":"12.8","Difficulty":"MASTER","Hot":"1"},
    {"Name":"Here We Go","Constant":"12.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Hey-day狂騒曲（カプリチオ）","Constant":"12.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"High Free Spirits","Constant":"12.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"HONEY-Q","Constant":"13.8","Difficulty":"MASTER","Hot":"1"},
    {"Name":"Hyper Active","Constant":"12.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Imperishable Night 2006 (2016 Refine)","Constant":"13.8","Difficulty":"MASTER","Hot":"1"},
    {"Name":"Jump!! Jump!! Jump!!","Constant":"12.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Kattobi KEIKYU Rider","Constant":"13.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Kiss Me Kiss","Constant":"12.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Lazy Addiction","Constant":"13.8","Difficulty":"MASTER","Hot":"1"},
    {"Name":"Link of Destiny","Constant":"12.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Link with U","Constant":"12.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Los! Los! Los!","Constant":"11.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Lost Princess","Constant":"11.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Love is MY RAIL","Constant":"12.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"MAKING！ハイタッチ！","Constant":"12.9","Difficulty":"MASTER","Hot":"1"},
    {"Name":"Maqrite","Constant":"13.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Mare Maris","Constant":"12.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"MEGATON BLAST","Constant":"14.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Melody！","Constant":"12.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"METEOR","Constant":"12.5","Difficulty":"MASTER","Hot":"1"},
    {"Name":"Mini skirt","Constant":"13.9","Difficulty":"MASTER","Hot":"1"},
    {"Name":"Necro Fantasia","Constant":"12.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"oboro","Constant":"12.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"only my railgun","Constant":"12.1","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Opera of the wasteland","Constant":"13","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Opfer","Constant":"14.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Oshama Scramble!","Constant":"13.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"P！P！P！P！がおー!!","Constant":"12.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Paqqin","Constant":"13.1","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Paradise Lost","Constant":"12.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Perfect Shining!!","Constant":"11.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Petit Etoile","Constant":"13.4","Difficulty":"MASTER","Hot":"1"},
    {"Name":"Preserved Roses","Constant":"12.4","Difficulty":"MASTER","Hot":"1"},
    {"Name":"Red “reduction division” -crossroads version-","Constant":"12.2","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Red Battle","Constant":"12.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Redo","Constant":"12.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Rising Hope","Constant":"13","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Rule the World!!","Constant":"12.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"SAKURA","Constant":"10.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"SAVIOR OF SONG","Constant":"12.2","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Scream out! -音華鏡 Re:BREAK-","Constant":"13.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"secret base ～君がくれたもの～ (10 years after Ver.)","Constant":"11.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Sentimental Snow","Constant":"11.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"SILENT BLUE","Constant":"14.1","Difficulty":"MASTER","Hot":"1"},
    {"Name":"sister's noise","Constant":"12.1","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Star Divine","Constant":"12.4","Difficulty":"MASTER","Hot":"1"},
    {"Name":"Starring Stars","Constant":"12.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"STARTLINER","Constant":"11","Difficulty":"MASTER","Hot":"0"},
    {"Name":"STEP by STEP UP↑↑↑↑","Constant":"12.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"sweet little sister","Constant":"13","Difficulty":"MASTER","Hot":"0"},
    {"Name":"SWEET SHAKE!!","Constant":"12.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Sword of Secret","Constant":"13.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"TAKE ON THE WORLD","Constant":"13.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"TeA","Constant":"12.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Tell Your World","Constant":"11.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"That Is How I Roll!","Constant":"11","Difficulty":"MASTER","Hot":"0"},
    {"Name":"The Everlasting Guilty Crown","Constant":"12.7","Difficulty":"MASTER","Hot":"1"},
    {"Name":"The Formula","Constant":"12.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"The wheel to the right","Constant":"13.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"This game","Constant":"11.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Titania","Constant":"14.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"TOMORROW","Constant":"11.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Touch and Go","Constant":"13.4","Difficulty":"MASTER","Hot":"1"},
    {"Name":"UTAKATA","Constant":"13","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Viyella's Tears","Constant":"14.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"We Gonna Journey","Constant":"13.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"What color...","Constant":"12.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"World Vanquisher","Constant":"14.5","Difficulty":"MASTER","Hot":"1"},
    {"Name":"Y.Y.Y.計画!!!!","Constant":"12.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"YURUSHITE","Constant":"14.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"Zest of Blue","Constant":"12","Difficulty":"MASTER","Hot":"0"},
    {"Name":"アクアテラリウム","Constant":"12","Difficulty":"MASTER","Hot":"0"},
    {"Name":"アリサのテーマ","Constant":"13.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"アンハッピーリフレイン","Constant":"13","Difficulty":"MASTER","Hot":"0"},
    {"Name":"いーあるふぁんくらぶ","Constant":"11.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"インビジブル","Constant":"13.7","Difficulty":"MASTER","Hot":"1"},
    {"Name":"ウサテイ","Constant":"13.2","Difficulty":"MASTER","Hot":"1"},
    {"Name":"えがおのオーケストラっ！","Constant":"10.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"エピクロスの虹はもう見えない","Constant":"13.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"エンドマークに希望と涙を添えて","Constant":"14.2","Difficulty":"MASTER","Hot":"0"},
    {"Name":"おこちゃま戦争","Constant":"12","Difficulty":"MASTER","Hot":"0"},
    {"Name":"オモイヨシノ","Constant":"12","Difficulty":"MASTER","Hot":"0"},
    {"Name":"オンゲキ全域★アカネサマ？","Constant":"13.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"かくしん的☆めたまるふぉ～ぜっ!","Constant":"12.1","Difficulty":"MASTER","Hot":"0"},
    {"Name":"カミサマネジマキ","Constant":"13.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"からくりピエロ","Constant":"12.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"カンペキWill","Constant":"11.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ギガンティックO.T.N","Constant":"13.7","Difficulty":"MASTER","Hot":"1"},
    {"Name":"キミノヨゾラ哨戒班","Constant":"12.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"クイーンオブハート","Constant":"13.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"グリーンライツ・セレナーデ","Constant":"12.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ゴーカ！ごーかい！？ファントムシーフ！","Constant":"13.1","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ゴーストルール","Constant":"12.2","Difficulty":"MASTER","Hot":"0"},
    {"Name":"こころここから","Constant":"12.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"サドマミホリック","Constant":"13.7","Difficulty":"MASTER","Hot":"1"},
    {"Name":"サマータイムレコード","Constant":"12","Difficulty":"MASTER","Hot":"1"},
    {"Name":"シャルル","Constant":"12","Difficulty":"MASTER","Hot":"0"},
    {"Name":"シュガーソングとビターステップ","Constant":"11.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"しゅわりん☆どり〜みん","Constant":"10.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"タテマエと本心の大乱闘","Constant":"11.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ダンスロボットダンス","Constant":"12.8","Difficulty":"MASTER","Hot":"1"},
    {"Name":"チュルリラ・チュルリラ・ダッダッダ！","Constant":"12.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"チルノのパーフェクトさんすう教室","Constant":"12.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ですのっ！White ＆ Black","Constant":"12.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"どうぶつ☆パラダイス","Constant":"12.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ドーナツホール","Constant":"13.1","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ときめきエクスペリエンス！","Constant":"10.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"トリドリ⇒モリモリ！Lovely fruits☆","Constant":"12.3","Difficulty":"MASTER","Hot":"1"},
    {"Name":"ナイト・オブ・ナイツ","Constant":"12.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ナイト・オブ・ナイツ (Cranky Remix)","Constant":"13.5","Difficulty":"MASTER","Hot":"1"},
    {"Name":"ネ！コ！","Constant":"12.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ヒバナ","Constant":"12.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ヒビカセ","Constant":"12.1","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ファッとして桃源郷","Constant":"12.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ブツメツビーターズ","Constant":"13.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ブリキノダンス","Constant":"11.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ブレス・ユア・ブレス","Constant":"11.8","Difficulty":"MASTER","Hot":"1"},
    {"Name":"ぼくらの16bit戦争","Constant":"13.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ポケットからぬりつぶせ！","Constant":"12.3","Difficulty":"MASTER","Hot":"1"},
    {"Name":"まっすぐ→→→ストリーム！","Constant":"12.8","Difficulty":"MASTER","Hot":"1"},
    {"Name":"みんな Happy!!","Constant":"11.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"メーベル (self cover)","Constant":"11.9","Difficulty":"MASTER","Hot":"1"},
    {"Name":"メニメニマニマニ","Constant":"13.1","Difficulty":"MASTER","Hot":"0"},
    {"Name":"メルト","Constant":"11.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"めんどーい！やっほーい！ともだち！","Constant":"12.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ゆら・ゆらRing-Dong-Dance","Constant":"12.1","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ようこそジャパリパークへ","Constant":"11.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"レプリカの恋","Constant":"12.2","Difficulty":"MASTER","Hot":"1"},
    {"Name":"れみりあ☆デスティニー","Constant":"12.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ロキ","Constant":"12.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ロッキンピンクモンスター","Constant":"12.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ロボットプラネットユートピア","Constant":"13.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"わたし音頭","Constant":"11.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"永遠メモリー","Constant":"12.4","Difficulty":"MASTER","Hot":"1"},
    {"Name":"回レ！雪月花","Constant":"11.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"快晴","Constant":"12.3","Difficulty":"MASTER","Hot":"1"},
    {"Name":"寒想桜","Constant":"12.1","Difficulty":"MASTER","Hot":"0"},
    {"Name":"患部で止まってすぐ溶ける～狂気の優曇華院","Constant":"13.3","Difficulty":"MASTER","Hot":"1"},
    {"Name":"鬼KYOKAN","Constant":"12.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"極上スマイル","Constant":"11.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"銀のめぐり","Constant":"13.2","Difficulty":"MASTER","Hot":"1"},
    {"Name":"君の知らない物語","Constant":"10.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"月に叢雲華に風","Constant":"12.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"幻想のサテライト","Constant":"12.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"光線チューニング","Constant":"12.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"幸せになれる隠しコマンドがあるらしい","Constant":"13.2","Difficulty":"MASTER","Hot":"0"},
    {"Name":"今ぞ♡崇め奉れ☆オマエらよ！！～姫の秘メタル渇望～","Constant":"13.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"混沌を越えし我らが神聖なる調律主を讃えよ","Constant":"14.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"砂の惑星 feat. HATSUNE MIKU","Constant":"12.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"最強 the サマータイム!!!!!","Constant":"12.4","Difficulty":"MASTER","Hot":"1"},
    {"Name":"最終鬼畜妹フランドール・Ｓ","Constant":"13.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"四次元跳躍機関","Constant":"12.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"時の冒険者","Constant":"13","Difficulty":"MASTER","Hot":"0"},
    {"Name":"終わりの先の音節","Constant":"13.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"初音ミクの激唱","Constant":"13.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"初音ミクの消失","Constant":"13.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"心","Constant":"14.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"心象蜃気楼","Constant":"12.2","Difficulty":"MASTER","Hot":"0"},
    {"Name":"神威","Constant":"14.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"進捗どうですか？","Constant":"12.6","Difficulty":"MASTER","Hot":"0"},
    {"Name":"人生リセットボタン","Constant":"13.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"人類みなセンパイ！","Constant":"12.6","Difficulty":"MASTER","Hot":"1"},
    {"Name":"星のダイアローグ","Constant":"11.7","Difficulty":"MASTER","Hot":"1"},
    {"Name":"星屑ユートピア","Constant":"13","Difficulty":"MASTER","Hot":"0"},
    {"Name":"青春サイダー","Constant":"13","Difficulty":"MASTER","Hot":"1"},
    {"Name":"千本桜","Constant":"11.8","Difficulty":"MASTER","Hot":"0"},
    {"Name":"閃鋼のブリューナク","Constant":"13.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"全力ハッピーライフ","Constant":"13.4","Difficulty":"MASTER","Hot":"1"},
    {"Name":"超電磁少女Days","Constant":"12.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"鳥の詩","Constant":"11","Difficulty":"MASTER","Hot":"0"},
    {"Name":"天ノ弱","Constant":"11.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"天火明命","Constant":"13","Difficulty":"MASTER","Hot":"0"},
    {"Name":"徒花ネクロマンシー","Constant":"12.6","Difficulty":"MASTER","Hot":"1"},
    {"Name":"怒槌","Constant":"14.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"東方妖々夢 ～the maximum moving about～","Constant":"12.7","Difficulty":"MASTER","Hot":"0"},
    {"Name":"透明声彩","Constant":"12.4","Difficulty":"MASTER","Hot":"1"},
    {"Name":"脳漿炸裂ガール","Constant":"13.2","Difficulty":"MASTER","Hot":"0"},
    {"Name":"本能的 Survivor","Constant":"12.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"未来の彼方","Constant":"12.5","Difficulty":"MASTER","Hot":"1"},
    {"Name":"妄想感傷代償連盟","Constant":"12.2","Difficulty":"MASTER","Hot":"0"},
    {"Name":"木彫り鯰と右肩ゾンビ","Constant":"12.2","Difficulty":"MASTER","Hot":"0"},
    {"Name":"夜明けのストリング","Constant":"12.1","Difficulty":"MASTER","Hot":"1"},
    {"Name":"妖狐仙楽踏","Constant":"13.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"流星","Constant":"12.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"連れ去って・閉じ込めて・好きにして","Constant":"10.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"炉心融解","Constant":"12.4","Difficulty":"MASTER","Hot":"0"},
    {"Name":"六兆年と一夜物語","Constant":"12.5","Difficulty":"MASTER","Hot":"0"},
    {"Name":"彗星ハネムーン","Constant":"12.5","Difficulty":"MASTER","Hot":"1"},
    {"Name":"檄!帝国華撃団","Constant":"11.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"櫻結び","Constant":"12.3","Difficulty":"MASTER","Hot":"0"},
    {"Name":"ω4","Constant":"14.9","Difficulty":"MASTER","Hot":"0"},
    {"Name":"39","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"＊ハロー、プラネット。","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"7thSense","Constant":"11.7","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ADAMAS","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"Aenbharr","Constant":"12.6","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Ai Nov","Constant":"11","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"AMAZING MIGHTYYYY!!!!","Constant":"10.7","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Äventyr","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Bad Apple!! feat.nomico","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Baqeela","Constant":"11.4","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"BLACK SHOUT","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"BOUNCE & DANCE","Constant":"10.7","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Brain Power","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Calamity Fortune","Constant":"11.9","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Chelly spLash♪♪","Constant":"10.9","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"CiRCLING","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Colors","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"conflict","Constant":"11.4","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Connecting Happy!!","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Cream+Mint","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Cyberozar","Constant":"10","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"DAYBREAK FRONTLINE","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Dazzle hop","Constant":"12.3","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Death Doll","Constant":"11.2","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Desperado Waltz","Constant":"12.3","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"Destiny Runner","Constant":"10","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Doll's Destiny","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"Dolphika","Constant":"10.7","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Dragoon","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"DreamRiser","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Energy Booster ～ 上海紅茶館","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Everlasting Today","Constant":"12.1","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"fantastic dreamer","Constant":"10","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"First Twinkle","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"FREEDOM DiVE (tpz Overcute Remix)","Constant":"11.7","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"fulgente","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"GAME IS LIFE","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Garakuta Doll Play","Constant":"12.9","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Gate of Doom","Constant":"11","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"GEOMETRIC DANCE","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"GO! GO! MANIAC","Constant":"10.6","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"ＧＯ！ＧＯ！ラブリズム♥","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"God knows...","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"GOODRAGE","Constant":"11.5","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Grand symphony","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"GranFatalité","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Grip & Break down !!","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Halcyon","Constant":"11","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Hand in Hand","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"HARMONIZE","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Hello","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"Help me","Constant":"10","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"Here We Go","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Hey-day狂騒曲（カプリチオ）","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"High Free Spirits","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"HONEY-Q","Constant":"11.8","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"Hyper Active","Constant":"11.2","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Imperishable Night 2006 (2016 Refine)","Constant":"11.6","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"Jump!! Jump!! Jump!!","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Kattobi KEIKYU Rider","Constant":"10.8","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Kiss Me Kiss","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Lazy Addiction","Constant":"11.6","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"Link of Destiny","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Link with U","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Los! Los! Los!","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Lost Princess","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Love is MY RAIL","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"MAKING！ハイタッチ！","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"Maqrite","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Mare Maris","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"MEGATON BLAST","Constant":"13.1","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Melody！","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"METEOR","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"Mini skirt","Constant":"12.2","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"Necro Fantasia","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"oboro","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"only my railgun","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Opera of the wasteland","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Opfer","Constant":"13.4","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Oshama Scramble!","Constant":"10.2","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"P！P！P！P！がおー!!","Constant":"10.7","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Paqqin","Constant":"10.7","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Paradise Lost","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Perfect Shining!!","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Petit Etoile","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"Preserved Roses","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"Red “reduction division” -crossroads version-","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Red Battle","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Redo","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Rising Hope","Constant":"10.1","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Rule the World!!","Constant":"10.1","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"SAKURA","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"SAVIOR OF SONG","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Scream out! -音華鏡 Re:BREAK-","Constant":"10.9","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"secret base ～君がくれたもの～ (10 years after Ver.)","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Sentimental Snow","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"SILENT BLUE","Constant":"12.1","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"sister's noise","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Star Divine","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"Starring Stars","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"STARTLINER","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"STEP by STEP UP↑↑↑↑","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"sweet little sister","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"SWEET SHAKE!!","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Sword of Secret","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"TAKE ON THE WORLD","Constant":"10.2","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"TeA","Constant":"10","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Tell Your World","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"That Is How I Roll!","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"The Everlasting Guilty Crown","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"The Formula","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"The wheel to the right","Constant":"12.2","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"This game","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Titania","Constant":"13.2","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"TOMORROW","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Touch and Go","Constant":"11.1","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"UTAKATA","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Viyella's Tears","Constant":"13.3","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"We Gonna Journey","Constant":"10.4","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"What color...","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"World Vanquisher","Constant":"11.9","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"Y.Y.Y.計画!!!!","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"YURUSHITE","Constant":"12.3","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"Zest of Blue","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"アクアテラリウム","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"アリサのテーマ","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"アンハッピーリフレイン","Constant":"11.3","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"いーあるふぁんくらぶ","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"インビジブル","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"ウサテイ","Constant":"11","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"えがおのオーケストラっ！","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"エピクロスの虹はもう見えない","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"エンドマークに希望と涙を添えて","Constant":"11.8","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"おこちゃま戦争","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"オモイヨシノ","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"オンゲキ全域★アカネサマ？","Constant":"10.8","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"かくしん的☆めたまるふぉ～ぜっ!","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"カミサマネジマキ","Constant":"11.7","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"からくりピエロ","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"カンペキWill","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ギガンティックO.T.N","Constant":"10.8","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"キミノヨゾラ哨戒班","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"クイーンオブハート","Constant":"10.7","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"グリーンライツ・セレナーデ","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ゴーカ！ごーかい！？ファントムシーフ！","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ゴーストルール","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"こころここから","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"サドマミホリック","Constant":"10.9","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"サマータイムレコード","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"シャルル","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"シュガーソングとビターステップ","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"しゅわりん☆どり〜みん","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"タテマエと本心の大乱闘","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ダンスロボットダンス","Constant":"10.5","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"チュルリラ・チュルリラ・ダッダッダ！","Constant":"10","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"チルノのパーフェクトさんすう教室","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ですのっ！White ＆ Black","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"どうぶつ☆パラダイス","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ドーナツホール","Constant":"10.1","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ときめきエクスペリエンス！","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"トリドリ⇒モリモリ！Lovely fruits☆","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"ナイト・オブ・ナイツ","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ナイト・オブ・ナイツ (Cranky Remix)","Constant":"10.8","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"ネ！コ！","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ヒバナ","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ヒビカセ","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ファッとして桃源郷","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ブツメツビーターズ","Constant":"9.9","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ブリキノダンス","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ブレス・ユア・ブレス","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"ぼくらの16bit戦争","Constant":"10.3","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ポケットからぬりつぶせ！","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"まっすぐ→→→ストリーム！","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"みんな Happy!!","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"メーベル (self cover)","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"メニメニマニマニ","Constant":"10.6","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"メルト","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"めんどーい！やっほーい！ともだち！","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ゆら・ゆらRing-Dong-Dance","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ようこそジャパリパークへ","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"レプリカの恋","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"れみりあ☆デスティニー","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ロキ","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ロッキンピンクモンスター","Constant":"10.8","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ロボットプラネットユートピア","Constant":"10.4","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"わたし音頭","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"永遠メモリー","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"回レ！雪月花","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"快晴","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"寒想桜","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"患部で止まってすぐ溶ける～狂気の優曇華院","Constant":"10.6","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"鬼KYOKAN","Constant":"10.5","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"極上スマイル","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"銀のめぐり","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"君の知らない物語","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"月に叢雲華に風","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"幻想のサテライト","Constant":"10.3","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"光線チューニング","Constant":"10","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"幸せになれる隠しコマンドがあるらしい","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"今ぞ♡崇め奉れ☆オマエらよ！！～姫の秘メタル渇望～","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"混沌を越えし我らが神聖なる調律主を讃えよ","Constant":"12.9","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"砂の惑星 feat. HATSUNE MIKU","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"最強 the サマータイム!!!!!","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"最終鬼畜妹フランドール・Ｓ","Constant":"10.3","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"四次元跳躍機関","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"時の冒険者","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"終わりの先の音節","Constant":"11","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"初音ミクの激唱","Constant":"11","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"初音ミクの消失","Constant":"11.7","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"心","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"心象蜃気楼","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"神威","Constant":"12","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"進捗どうですか？","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"人生リセットボタン","Constant":"11.3","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"人類みなセンパイ！","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"星のダイアローグ","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"星屑ユートピア","Constant":"11.1","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"青春サイダー","Constant":"10.7","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"千本桜","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"閃鋼のブリューナク","Constant":"10.4","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"全力ハッピーライフ","Constant":"10.5","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"超電磁少女Days","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"鳥の詩","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"天ノ弱","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"天火明命","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"徒花ネクロマンシー","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"怒槌","Constant":"12.8","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"東方妖々夢 ～the maximum moving about～","Constant":"10","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"透明声彩","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"脳漿炸裂ガール","Constant":"10","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"本能的 Survivor","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"未来の彼方","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"妄想感傷代償連盟","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"木彫り鯰と右肩ゾンビ","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"夜明けのストリング","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"妖狐仙楽踏","Constant":"10.7","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"流星","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"連れ去って・閉じ込めて・好きにして","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"炉心融解","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"六兆年と一夜物語","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"彗星ハネムーン","Constant":"","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"檄!帝国華撃団","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"櫻結び","Constant":"","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"ω4","Constant":"13.4","Difficulty":"EXPERT","Hot":"0"},
    {"Name":"A Man In The Mirror","Constant":"13.2","Difficulty":"EXPERT","Hot":"1"},
    {"Name":"A Man In The Mirror","Constant":"14.8","Difficulty":"MASTER","Hot":"1"},
    {"Name":"感情アクセラレイション","Constant":"12.8","Difficulty":"MASTER","Hot":"1"},
    {"Name":"デリヘル呼んだら君が来た","Constant":"13.0","Difficulty":"MASTER","Hot":"1"},
    {"Name":"裏表ラバーズ","Constant":"13.9","Difficulty":"MASTER","Hot":"1"}
    ];
